### ISSUE TITLE
Exception seen

### ISSUE THREAD

**Issue by jeme** [dotJEM/json-storage#8]
System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_stress.changelog'. Cannot insert duplicate key in object 'dbo.stress.changelog'. The duplic
ate key value is (36062).
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject
 stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at DotJEM.Json.Storage.Adapter.SqlServerStorageAreaLog.Insert(Guid id, JObject original, JObject changed, ChangeType action) in F:\Github\json-storage\DotJEM.Json.Storage\Adapte
r\IStorageAreaLog.cs:line 156
   at DotJEM.Json.Storage.Adapter.SqlServerStorageArea.Insert(String contentType, JObject json) in F:\Github\json-storage\DotJEM.Json.Storage\Adapter\IStorageArea.cs:line 147
   at DotJEM.Json.Storage.Stress.ChangeProducer.Execute() in F:\Github\json-storage\DotJEM.Json.Storage.Stress\Program.cs:line 137
   at DotJEM.Json.Storage.Stress.ScheduledTask.ExecuteCallback() in F:\Github\json-storage\DotJEM.Json.Storage.Stress\Program.cs:line 259
ClientConnectionId:1ba8d932-06ba-459c-915f-37134be8c9a6
Error Number:2627,State:1,Class:14

**Comment by jeme** [comment]
not seen for a long time
